
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT Licence"
[[mods]]
    modId="extrabiomes"
    version="0.0.1"
    displayName="ExtraBiomes"
    logoFile="extrabiomes_logo.png"
    authors="Win Epic Fin"
    description='''${mod_description}'''
[[dependencies.extrabiomes]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrabiomes]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.3.0.3,)"
    ordering="NONE"
    side="BOTH"
